### PR TITLE
apply gcc patch for future proofing osx version checks

### PR DESCRIPTION
**Pull request by alexjbest**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by alexjbest** [comment]
@conda-forge-admin, please rerender

**Comment by alexjbest** [comment]
@conda-forge-admin, please rerender

**Comment by alexjbest** [comment]
@conda-forge-admin, please rerender

**Comment by alexjbest** [comment]
@conda-forge-admin, please rerender

**Comment by alexjbest** [comment]
@isuruf I believe the only failures on azure are now from tests on windows (where we hope it builds but wouldn't necessarily expect the tests to wokr?), so I would hesitantly say this is ready for review now.

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Pull request merged**
