### PR TITLE
Update to 7.5.0 and linux support

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by beckermr** [comment]
Why are we building this on drone?

**Comment by isuruf** [comment]
> Why are we building this on drone?

It's a cross compiler.

**Comment by beckermr** [comment]
Sure but we don’t need to cross compile from aarch to OS X. Only building on Linux would be sufficient.

**Comment by isuruf** [comment]
Does it hurt?

**Comment by beckermr** [comment]
*linux-64

**Comment by beckermr** [comment]
It doesn’t hurt necessarily. I was wondering if there was a technical reason but it sounds like not.

**Pull request merged**
