### PR TITLE
gfortran 13.2.0

### PR DESCRIPTION
**Pull request by h-vetinari**
We've had the linux side for a [while](https://github.com/conda-forge/ctng-compilers-feedstock/pull/111) already, close the gap.

### CODE REVIEW

**Comment by h-vetinari** [comment]
@conda-forge/gfortran_impl_osx-64 
This is ready for review, PTAL! :)

**Comment by h-vetinari** [comment]
Upon closer inspection, the ppc builds have been failing on main for long time already (last passing run on travis is more than a year ago). Together with the fact that compiling to osx from linux is pretty rare AFAICT, I feel confident to say that we're never going to use aarch64 or ppc64le for that, if we can also do it from linux-64.

So I propose to just drop those builds.

**Comment by beckermr** [comment]
@isuruf said he used those builds IIRC so at least let's keep them and let them fail. He can fix if he needs them still.

**Comment by h-vetinari** [comment]
> He can fix if he needs them still.

If possible, I'd prefer to discuss directly, not in the third person.

@isuruf, are the ppc builds here important to you (I cannot see the use case...)? If so, is there a reason not to simply readd them if and when you come around to fixing them? I don't see the benefit of keeping red CI when it could trivially be readded later.

**Comment by h-vetinari** [comment]
Aside from removing the builds that have been failing for a year (and which are trivial to re-add in case they get fixed), this ends up being a very vanilla version update, so I'll put this in.

**Pull request merged**
