### PR TITLE
More GCC for osx-x64, new arm builds, version updates

### PR DESCRIPTION
**Pull request by h-vetinari**
Build gcc 10/11 also for osx-x64, bump gcc 9 to 9.4, simplify recipe a bit, move arm builds to be based on released versions (rather than untagged commits).

### CODE REVIEW

**Comment by h-vetinari** [comment]
Not sure what's happening with all the permission errors here, I didn't change anything about the build procedure itself:
```
echo "x86_64-apple-darwin13.4.0-clang++ -no-pie   -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -std=c++11 -fmessage-length=0 -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/gfortran_impl_osx-64-10.3.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -isysroot /Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -Wno-array-bounds -Wno-unknown-warning-option -Wno-deprecated -Wno-mismatched-tags -Wno-unused-command-line-argument -Wno-ignored-attributes -DIN_GCC    -fno-strict-aliasing -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wno-error=format-diag -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -Wl,-no_pie -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,$PREFIX/lib -L$PREFIX/lib -L/Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/lib" > checksum-options.tmp \
&& ../../gcc/../move-if-change checksum-options.tmp checksum-options
awk -f ../../gcc/config/i386/i386-builtin-types.awk ../../gcc/config/i386/i386-builtin-types.def > tmp-bt.inc
/bin/sh ../../gcc/../move-if-change tmp-bt.inc i386-builtin-types.inc
echo timestamp > s-i386-bt
cp ../../gcc/gcc-ar.c gcc-nm.c
make[2]: cp: Permission denied
```

**Comment by h-vetinari** [comment]
Ah, the error for osx-arm 11.1 was hiding further up the log:
```
checking for unistd.h... (cached) yes
configure: updating cache ./config.cache
configure: error: conditional "ENABLE_DARWIN_AT_RPATH" was never defined.
Usually this means the macro was only invoked conditionally.
checking that generated files are newer than configure... done
yes
make: *** [Makefile:9477: configure-zlib] Error 1
make: *** Waiting for unfinished jobs....
```

Still not sure what's happening with the permission errors on osx, as I didn't touch the build scripts at all...

**Comment by isuruf** [comment]
Upstream issue https://github.com/iains/gcc-darwin-arm64/issues/81

**Comment by isuruf** [comment]
@conda-forge-admin, rerender.

**Comment by erykoff** [comment]
Very strange; I just did `mamba build recipe -m .ci_support/osx_64_cross_target_platformosx-arm64gfortran_version11.2.0.yaml` with this branch on my old x86 macos laptop and it completed without errors.

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by isuruf** [comment]
Thanks for the PR

**Pull request merged**
