### PR TITLE
add support for 12.2.0 and drop 9.x and 10.x

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by alexjbest** [comment]
Hi @isuruf @beckermr, what is the status of this PR (sorry conda newbie here), anything I can do to push it forward?
I'm failing to build scipy (as part of the build process of https://github.com/sagemath/sage from source via conda) on OSX ventura (v 13.1.0)
Here at some step of the build I see an error
```
 /usr/local/Caskroom/mambaforge/base/envs/sage-build/bin/x86_64-apple-darwin13.4.0-gfortran -E -dM -
<built-in>: error: unknown value ‘13.1.0’ of ‘-mmacosx-version-min’
```
I believe the gcc patches 6725f186cb70d48338f69456864bf469a12ee5be or add1adaa17a294ea25918ffb4fdd40f115362632 should fix this in 12.2.0, so I'd love to either backport those or upgrade gfortran to 12.2.0 so nobody else gets bitten by this (a workaround for now is to set `export MACOSX_DEPLOYMENT_TARGET=12`)

**Comment by alexjbest** [comment]
@conda-forge-admin, rerender

**Comment by isuruf** [comment]
That was fixed in https://github.com/conda-forge/gfortran_impl_osx-64-feedstock/pull/61
Please open a new issue with the details in the issue template.

**Comment by alexjbest** [comment]
> That was fixed in #61 Please open a new issue with the details in the issue template.

Well I guess its a different issue to #61 if the changes from that PR are live on conda-forge and I still have the issue?
I hesitated to open a new issue as I figured it was essentially a duplicate of this PR, but here is #63 if thats what you prefer

**Comment by erykoff** [comment]
@isuruf Where did the mega-arm-patch come from?

**Comment by erykoff** [comment]
Ah, found it https://raw.githubusercontent.com/Homebrew/formula-patches/1d184289/gcc/gcc-12.2.0-arm.diff

**Pull request closed without merging**
