### PR TITLE
osx-arm64

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
That was fast! I guess someone found the time to port it after all!

**Comment by beckermr** [comment]
Impressive as usual @isuruf! Well done and huzzah!

cc @conda-forge/core

**Comment by jakirkham** [comment]
Nice! So we can now build Fortran things on macOS ARM or is there still more to do there?

**Comment by xhochy** [comment]
Awesome @isuruf !

**Comment by wolfv** [comment]
Just wondering, does this include these fixes? https://twitter.com/fxcoudert/status/1302564426206375942

**Comment by isuruf** [comment]
@wolfv, not yet.

**Pull request merged**
