### PR TITLE
Swap libgomp with llvm-openmp

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

See https://github.com/conda-forge/conda-forge.github.io/issues/831

### CODE REVIEW

**Comment by beckermr** [comment]
This needs a build number bump.

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
I am confused as to how this swaps the libraries under the hood. The recipes still package `libgomp` and they don't make any symlinks to help downstream packages out during compilation.

**Comment by isuruf** [comment]
Forgot to commit changes to build.sh. :smile:

**Comment by beckermr** [comment]
Ahhh great. Are we ok with static builds not being swapped?

https://github.com/conda-forge/gfortran_impl_osx-64-feedstock/pull/11/files#diff-e178b687b10a71a3348107ae3154e44cR119

**Comment by isuruf** [comment]
Yes, that's fine for now. I don't think there are any packages in conda-forge, that links statically

**Review by beckermr — APPROVED** [review]
LGTM! 

I'll wait for you to merge since it was not clear if we should actually merge this (yet) given the other thread.

**Comment by isuruf** [comment]
Only `camb` will be affected

**Pull request merged**
